harlan-zw/nuxt-seo

- layer/components/SeoKit.vue
> fix(SeoKit): add missing import `titleCase`

- README.md
> docs: read me typo

- layer/composables/breacrumbs.ts
Explicitly annotated the 'route' parameter with the 'RouteRecord' type
> fix(breacrumbs.ts): Fix implicit 'any' type error

- docs/content/2.og-image/0.getting-started/5.credits.md
> docs: add links in credits

- docs/content/3.og-image/0.getting-started/3.your-first-template.md
> docs: typo for link

- docs/content/2.sitemap/4.api/0.config.md
Properly close some inline code tags.
No issue, quick fix.
> doc: fix typos

- docs/content/3.og-image/2.guides/1.cache.md
> docs: fix og-image cache

- docs/content/2.sitemap/4.api/nitro-hooks.md
> docs: Update nitro-hooks.md

- docs/content/2.sitemap/2.guides/3.cache.md
> doc: fix cacheMaxAgeSeconds type

- docs/content/10.site-config/0.getting-started/3.how-it-works.md
> docs: fix env variable names

- docs/content/3.og-image/3.guides/6.icons-and-images.md
> chore: update props of nuxt-icon

- docs/content/10.site-config/2.guides/debugging.md
Fix a spelling mistake on the docs
> Fix-Spelling-Mistake

- docs/content/3.og-image/4.api/2.nuxt-seo-template.md
> docs: fixed link to "NuxtSeo" template

- docs/pages/[...slug].vue
The link to npm minor release version returns 404 - added updated link, not sure how it affects other pages template pages beside nuxt-og-image.
thanks Halran
> docs: fixed NPM minor version link

- docs/content/1.robots/1.integrations/0.i18n.md
- docs/content/10.site-config/1.integrations/0.i18n.md
- docs/content/2.sitemap/1.integrations/0.i18n.md
Updates the links to point to the up to date docs website.
> docs: update Nuxt I18n links

- docs/content/0.nuxt-seo/2.seo-guides/1.going-live.md
fix Unlightouse domain extension as it was pointing to .com instead of .dev. I used the docs website search to find other mentions of Unlighthouse but didn't find any.
If you know of any other places where unlighthouse is referenced then we should probably check those too. I'm happy to update my PR to include them.
> docs: Unlightouse domain extension

- docs/content/2.sitemap/1.integrations/1.content.md
> docs: grammar

- docs/components/HeaderLinks.vue
before:
after: 
thanks for all the modules & work!
> docs: update headerlinks bg color on hover in dark mode

- package.json
- pnpm-lock.yaml
- src/module.ts
removed `chalk` as dependency and used `consola` instead.
> refactor: use consola instead of chalk

- docs/content/3.og-image/0.getting-started/6.faq.md
It seems that the FAQ in Nuxt OG image wrote the wrong version of Nuxt
> doc: fix faq in nuxt og image

- docs/content/1.robots/1.getting-started/0.features.md
fix grammatical errors in features.md
> docs: fix grammatical errors in features.md

- docs/content/3.og-image/6.migration-guide/v3.md
> fix migration guide typo

- docs/content/4.schema-org/2.guides/0.default-schema-org.md
Fixed a typo on documentation for opt-out. Relevant property should be "defaults" and not "default"
> doc: fixed opt-out property typo

- docs/content/3.og-image/0.getting-started/5.getting-familar-with-nuxt-og-image.md
In the documentation there is a gramma issue which this PR solves. There is a missing 'do' in the text.
n/a
n/a
> docs: fix typo

- docs/content/0.nuxt-seo/3.api/9.config.md
The page was a bit confusing so I've updated it to match the [source code](https://github.com/harlan-zw/nuxt-seo/blob/v2/module/src/module.ts)
> docs: typos, adding fallbackTitle

- docs/content/2.sitemap/4.api/schema.md
N/A
Updated Sitemap Schema documentation based on current types from https://github.com/nuxt-modules/sitemap/blob/main/src/runtime/types.ts#L286
> docs: Update sitemap schema

- docs/content/3.og-image/3.guides/7.styling.md
> docs(og-image): typo of `inline-css`

- docs/content/1.robots/2.guides/3.nuxt-config.md
- fix example code in the `Group Configuration` section
- surrounded in `robots`
- rename `comments` -> `comment` (see https://github.com/nuxt-modules/robots/blob/bd7ceed17dd32780e41bc3eb73afbe9e99bc478f/src/runtime/types.ts#L27)
- reordered to keep consistency with the actual outputs
> docs: update 3.nuxt-config.md

- docs/content/6.link-checker/0.getting-started/1.installation.md
the prev link was linked to Nuxt Sitemap instad of Link Checker
> docs(link-checker): update playground link to stackblitz

- docs/components/content/SchemaOrgNodeList.vue
A very small change to fix links with spaces
> docs: fix broken links

- docs/content/nuxtSeo/2.guides/0.using-the-modules.md
This PR fixes a simple issue where the robots.txt link was going to sitemap.xml
- [x ] 📖 Documentation (updates to the documentation or readme)
> doc: robots.txt link was linking to sitemap.xml

- docs/content/learn/0.mastering-meta/2.titles.md
Just fixed a couple of typos on the documentation :)
> docs: fix "seperator" typo
