layer/components/Breadcrumbs.vue

https://www.w3.org/WAI/ARIA/apg/patterns/breadcrumb/examples/breadcrumb/ shows valid `aria-label` usage for breadcrumbs.
Resolves #33

fix(breadcrumbs): correct aria label placement

---

docs/content/5.sitemap/2.guides/6.customising-ui.md

Add missing prefix to Customizing UI page
This commit adds missing prefix `sitemap:` to the [Customizing UI](https://nuxtseo.com/sitemap/guides/customising-ui) page of the `nuxt-simple-sitemap` documentation.

docs: add missing prefix to Customizing UI page

---

docs/content/2.sitemap/4.api/0.config.md

The v2 config README is not rendering correctly when you have backtick inside backtick

docs: backtick render error

---

docs/content/0.nuxt-seo/2.guides/1.title-templates.md

I just spot an error on https://nuxtseo.com/nuxt-seo/guides/title-templates 
Change `Speical` for `Special` 

doc: fix typo

---

docs/content/3.og-image/3.api/2.components.md

This PR fixes a typo where `components.md` has the title "Composables".
This leads to the side nav showing the incorrect page title:
Just a small thing that confused me, so I decided to edit and submit this PR. Thank you for your work 🙏

docs: update components title

---

docs/content/2.sitemap/2.guides/0.filtering-urls.md

Link `defineRouteRules`, adding the trailing `s`.
n/a
n/a

docs(sitemap): link `defineRouteRules`

---

docs/content/0.nuxt-seo/1.getting-started/1.installation.md

This MR is fixing some faulty links on the get started page. IMO the final solution would be to also fix the typo in the url (`getting-familar-with-nuxt-og-image` to `getting-familiar-with-nuxt-og-image` - famil**i**ar).

docs: Fix faulty links on "Install Nuxt SEO"

---

docs/content/10.site-config/2.guides/3.runtime-site-config.md

`updateSiteConfig` should require `event` as first parameter. I also made it a bit more clear what `e` is and separated the if block from the assignment for (subjectively) better readability.
n/a
n/a

docs(runtime-site-config): add missing event parameter

---

docs/content/10.site-config/4.api/1.update-site-config.md
docs/content/10.site-config/4.nitro-api/1.update-site-config.md

Added a word that's been accidentally skipped in documentation

docs: skipped word in documentation

---

docs/content/3.og-image/0.getting-started/5.getting-familar-with-nuxt-og-image.md
docs/content/3.og-image/4.api/2.nuxt-seo-template.md

The previous link was invalid, causing a 404 - page not found, and I thought a quick fix was needed.

docs: fix link url

---

docs/content/3.og-image/0.getting-started/5.getting-familar-with-nuxt-og-image.md

Fixed the links leading to a 404 page when trying to visit the templates in [OG-Image Tutorial: Part 3](https://nuxtseo.com/og-image/getting-started/getting-familar-with-nuxt-og-image#part-3-creating-your-own-template)
replaced 
`https://github.com/harlan-zw/nuxt-og-image/...`
with
`https://github.com/nuxt-modules/og-image/...`

doc: fixed GitHub Templates/Community URL

---

docs/components/docs/DocsTocLinks.vue
src/runtime/nuxt/composables/useBreadcrumbItems.ts

This is a very early PR to make this module compatible with [changes we expect to release in Nuxt v5](https://github.com/nuxt/nuxt/issues/25323).
In [Nuxt v3.7.0](https://github.com/nuxt/nuxt/releases/tag/v3.7.0) we added support for `import.meta.*` (see [original PR](https://github.com/nuxt/nuxt/pull/22428)) and we've been gradually updating docs and moving across from the old `process.*` patterned variables.
As I'm sure you're aware, these variables are replaced at build-time and enable tree-shaking in bundled code.
This change affects _runtime_ code (that is, that is processed by the Nuxt bundler, like vite or webpack) rather than code running in Node. So it really doesn't matter what the string is, but it makes more sense in an ESM-world to use `import.meta` rather than `process`.
(It …

fix: opt in to `import.meta.*` properties

---

README.md
docs/content/0.nuxt-seo/1.getting-started/1.installation.md
docs/content/1.robots/1.getting-started/0.installation.md
docs/content/2.sitemap/0.getting-started/1.installation.md
docs/content/3.og-image/0.getting-started/1.installation.md
docs/content/4.schema-org/0.getting-started/1.installation.md
docs/content/6.link-checker/0.getting-started/1.installation.md
docs/content/7.experiments/0.getting-started/1.installation.md

`nuxi module add` section has been added for `Nuxt SEO` in the #216 issue.
For documentation uniformity, the following modules also have sections added
- `simple-robots`
- `sitemap`
- `og-image`
- `schema-org`
- `link-checker`
- `seo-experiments`
`site-config` is not supported because the module was not yet added.
The documentation would like to addressed after the module is added.
- related: harlan-zw/nuxt-site-config#30
related #216 , harlan-zw/nuxt-site-config#30

docs: use new `nuxi module add` command in installation

---

README.md

In README.md, only the `nuxt-schema-org` link was different. 
Therefore, I have modified the link to the GitHub repo.

docs: fix links to `nuxt-schema-org`

---

docs/content/2.sitemap/0.getting-started/4.faq.md

Fixes typo. The previous "If _you're_ sitemap is validating…" expands to "If _you are_ sitemap is validating", which doesn't make sense. It's likely the intended start of the sentence is "If _your_ sitemap is validating…".

docs: fix typo

---

docs/content/0.nuxt-seo/3.api/_breadcrumb-raw.md

When copy pasting the example code it will give a 500 server error since the variables do not match

doc: broken breadcrumbs snippet

---

docs/content/0.nuxt-seo/2.guides/0.using-the-modules.md
docs/content/0.nuxt-seo/2.guides/2.title-templates.md
docs/content/0.nuxt-seo/2.guides/3.trailing-slashes.md
docs/content/0.nuxt-seo/6.migration-guide/0.nuxt-seo-kit.md
docs/content/1.robots/1.getting-started/how-it-works.md
docs/content/1.robots/3.nitro-api/2.nitro-hooks.md
docs/content/1.robots/4.releases/1.v4.md
docs/content/10.site-config/0.getting-started/0.background.md
docs/content/10.site-config/4.api/0.site-link.md
docs/content/10.site-config/4.api/config.md
docs/content/10.site-config/4.nitro-api/3.get-site-indexable.md
docs/content/2.sitemap/0.getting-started/2.data-sources.md
docs/content/2.sitemap/1.integrations/1.content.md
docs/content/2.sitemap/2.guides/4.route-rules.md
docs/content/2.sitemap/5.releases/v3.md
docs/content/3.og-image/3.guides/3.jpegs.md
docs/content/3.og-image/4.api/2.nuxt-seo-template.md
docs/content/3.og-image/4.api/3.config.md
docs/content/3.og-image/4.api/3.nuxt-hooks.md
docs/content/3.og-image/7.releases/v2.md
docs/content/3.og-image/7.releases/v3.md
docs/content/6.link-checker/4.api/0.config.md
docs/content/7.experiments/4.releases/v3.md

Fixed some spelling errors across the docs. 
Some words were adjusted to be consistent with en-GB spelling that looks to be used in the project. e.g. (behavior ->  behaviour, analyze -> analyse)

docs: fix spelling

---

src/runtime/nitro/middleware/redirect.ts

This PR changes the redirect to use the `site.url` config.
According to the docs, [`redirectToCanonicalSiteUrl` redirects to the default canonical url](https://nuxtseo.com/nuxt-seo/guides/redirect-canonical), which is supposed to be [`site.url`](https://nuxtseo.com/nuxt-seo/guides/default-meta#canonical), not `site.site`

fix: redirect using url config key

---

docs/content/0.nuxt-seo/2.guides/2.default-meta.md
src/module.ts
src/runtime/nuxt/logic/applyDefaults.ts

https://github.com/harlan-zw/nuxt-seo/issues/276
Adds support for having query params in the canonical URL, this is important when using query param pagination or searching.
Default whitelist:
```ts
[
'page',
'sort',
'filter',
'search',
'q',
'category',
'tag',
],
```

feat: `canonicalQueryWhitelist`

---

src/runtime/nuxt/composables/useBreadcrumbItems.ts

`useBreadcrumbItems()` does not work fetch page's meta from dynamic routes (e.g. `/items/[id]`). This proposes to fix that. This still doesn't solve the problem of dynamic labels as `definePageMeta` is a render macro and figuring out how to morph crumps with dynamic attributes is a different topic, but ability to use even static overrides in dynamic routes I think is usefull

fix: `useBreadcrumbItems` support static meta from dynamic routes

---

src/runtime/nuxt/composables/useBreadcrumbItems.ts

This PR introduces enhancements to the `useBreadcrumbItems` function in order to facilitate the dynamic updating of breadcrumbs, e. g. based on route parameters.
Resolves #327
- Changed the type of `overrides` in `BreadcrumbProps` from an array to `MaybeRefOrGetter<(BreadcrumbItemProps | false | undefined)[]>` to allow for computed values.
- Updated the assignment of `overrides` to use `toValue` for proper reactive handling of the `options.overrides`.

fix(breadcrumbs): support computed overrides
